vich_uploader:
    db_driver: orm

    mappings:
        application_form_images:
            uri_prefix: /images/application_form
            upload_destination: '%kernel.project_dir%/public/images/application_form'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        application_form_media:
            uri_prefix: /media/application_form
            upload_destination: '%kernel.project_dir%/public/media/application_form'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        application_form_qr:
            uri_prefix: /media/application_form_qr
            upload_destination: '%kernel.project_dir%/public/media/application_form_qr'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
